// <auto-generated />
using System;
using DiplomaManagementSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiplomaManagementSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623071738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("academic_years", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AnnualRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("AcademicYearId", "RoleType")
                        .IsUnique();

                    b.ToTable("annual_role_assignments", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StudyGroupId")
                        .HasColumnType("uuid");

                    b.Property<short>("UserKind")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudyGroupId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId");

                    b.HasIndex("PerformedAt");

                    b.HasIndex("PerformedById");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Semester")
                        .HasColumnType("integer");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.ToTable("defence_sessions", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Diploma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("AdmissionStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DefenceDate")
                        .HasColumnType("date");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<short>("LifecycleStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("ReviewAssignmentStatus")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<short>("SupervisorAssignmentStatus")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("StudentId", "DefenceSessionId")
                        .IsUnique();

                    b.ToTable("diplomas", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaAdmissionCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.Property<short?>("FormattingReviewOutcome")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSecretaryOverride")
                        .HasColumnType("boolean");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CompletedById");

                    b.HasIndex("DiplomaId");

                    b.HasIndex("DiplomaId", "Type")
                        .IsUnique();

                    b.ToTable("diploma_admission_checkpoints", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DiplomaId");

                    b.ToTable("diploma_comments", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaTopicVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("DiplomaId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("diploma_topic_versions", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.StudyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("study_groups", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.SupervisorPoolEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("DefenceSessionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("supervisor_pool_entries", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AnnualRoleAssignment", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany("AnnualRoleAssignments")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.StudyGroup", "StudyGroup")
                        .WithMany("Students")
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany()
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenceSession");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSession", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany("DefenceSessions")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Diploma", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("Diplomas")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefenceSession");

                    b.Navigation("Reviewer");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaAdmissionCheckpoint", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("AdmissionCheckpoints")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedBy");

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaComment", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("Comments")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaTopicVersion", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("TopicVersions")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Diploma");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.StudyGroup", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("StudyGroups")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.SupervisorPoolEntry", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("SupervisorPoolEntries")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.ApplicationUser", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenceSession");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AcademicYear", b =>
                {
                    b.Navigation("AnnualRoleAssignments");

                    b.Navigation("DefenceSessions");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSession", b =>
                {
                    b.Navigation("Diplomas");

                    b.Navigation("StudyGroups");

                    b.Navigation("SupervisorPoolEntries");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Diploma", b =>
                {
                    b.Navigation("AdmissionCheckpoints");

                    b.Navigation("Comments");

                    b.Navigation("TopicVersions");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.StudyGroup", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
